[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10.0

[font.normal]
family = "Adwaita Mono"

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "None"
opacity = 1.0
startup_mode = "Maximized"

[window.dimensions]
columns = 160
lines = 40

[general]
import = ["/home/ugzuzg/.config/alacritty/zenburn.toml"]
