[[colors.indexed_colors]]
color = "0xdfaf8f"
index = 16

[[colors.indexed_colors]]
color = "0x000000"
index = 17

[[colors.indexed_colors]]
color = "0x404040"
index = 18

[[colors.indexed_colors]]
color = "0x606060"
index = 19

[[colors.indexed_colors]]
color = "0x808080"
index = 20

[[colors.indexed_colors]]
color = "0xc0c0c0"
index = 21

[colors.bright]
black = "0x6f6f6f"
blue = "0x94BFF3"
cyan = "0x93e0e3"
green = "0x8FB28F"
magenta = "0xDC8CC3"
red = "0xECB3B3"
white = "0xffffef"
yellow = "0xf0dfaf"

[colors.cursor]
cursor = "0xdcdccc"
text = "0x3f3f3f"

[colors.normal]
black = "0x383838"
blue = "0x8cd0d3"
cyan = "0x93e0e3"
green = "0x7f9f7f"
magenta = "0xDC8CC3"
red = "0xCC9393"
white = "0xdcdccc"
yellow = "0xf0dfaf"

[colors.primary]
background = "0x3f3f3f"
foreground = "0xdcdccc"

[colors.footer_bar]
background = "0x494949"
foreground = "0xdcdccc"
