# This is basic configuration example for SpaceVim

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer, the value of this option is a string.
colorscheme = "zenburn"
colorscheme_bg = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors, the type of the value is boolean, true or false.
enable_guicolors = true
# Display file type icon on the tabline, If you do not have nerd fonts
# installed, please change the value to false
enable_tabline_filetype_icon = true
# Display current mode text on statusline, by default It is disabled,
# only color will be changed when switch modes.
enable_statusline_display_mode = false
enable_vimfiler_gitstatus = true
enable_os_fileformat_icon = true
enable_neomake = false
enable_ale = true
buffer_index_type = 4
default_indent = 2
bootstrap_after = "customise#after"


[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "cycle"

[[layers]]
name = "shell"
default_position = "top"
default_height = 30

[[layers]]
name = "lsp"
filetypes = [
  "javascript"
]

[[layers]]
name = "lang#python"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#clojure"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#xml"

[[layers]]
name = "operator"

[[layers]]
name = "git"

[[layers]]
name = "VersionControl"

[[layers]]
name = "denite"


[[custom_plugins]]
name = "benjie/local-npm-bin.vim"

[[custom_plugins]]
name = "posva/vim-vue"

[[custom_plugins]]
name = "jnurmine/Zenburn"

[[custom_plugins]]
name = "martinda/Jenkinsfile-vim-syntax"
