# This is basic configuration example for SpaceVim

# All SpaceVim option below [option] section
[options]
# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer, the value of this option is a string.
colorscheme = 'zenburn'
colorscheme_bg = 'dark'
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors, the type of the value is boolean, true or false.
enable_guicolors = true
# Display file type icon on the tabline, If you do not have nerd fonts
# installed, please change the value to false
enable_tabline_filetype_icon = true
# Display current mode text on statusline, by default It is disabled,
# only color will be changed when switch modes.
enable_statusline_display_mode = true
enable_vimfiler_gitstatus = true
enable_os_fileformat_icon = true
enable_neomake = false
enable_ale = true
lint_on_the_fly = true
buffer_index_type = 4
default_indent = 2
bootstrap_before = 'customise#before'
bootstrap_after = 'customise#after'
statusline_separator = 'arrow'
disabled_plugins = []
filemanager = 'defx'

# autocomplete configuration
autocomplete_method = 'deoplete'
autocomplete_parens = false

[[layers]]
name = 'checkers'

[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = 'complete'
auto-completion-tab-key-behavior = 'cycle'
auto_completion_complete_with_key_sequence = 'nil'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'lsp'
filetypes = [
  'javascript',
  'typescript'
]

[[layers]]
name = 'lang#typescript'

[[layers]]
name = 'lang#vue'

[[layers]]
name = 'lang#html'

[[layers]]
name = 'lang#rust'

[[layers]]
name = 'lang#toml'

[[layers]]
name = 'lang#vim'

[[layers]]
name = 'lang#xml'

[[layers]]
name = 'lang#markdown'

[[layers]]
name = 'operator'

[[layers]]
name = 'git'
git-plugin = 'gina'

[[layers]]
name = 'VersionControl'

[[layers]]
name = 'denite'

[[layers]]
name = 'sudo'


[[custom_plugins]]
name = 'benjie/local-npm-bin.vim'

[[custom_plugins]]
name = 'jnurmine/Zenburn'

[[custom_plugins]]
name = 'neoclide/vim-jsx-improve'

[[custom_plugins]]
name = 'prettier/vim-prettier'

[[custom_plugins]]
name = 'wakatime/vim-wakatime'

[[custom_plugins]]
name = 'jceb/vim-orgmode'
