[git.files]
"git/.gitconfig" = "~/.gitconfig"

[zsh.files]
"zsh/.zshenv" = "~/.zshenv"
"zsh/config" = "~/.config/zsh"

[alacritty.files]
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"
"alacritty/zenburn.toml" = "~/.config/alacritty/zenburn.toml"

[gnome.files]
"gnome/autostart/unlock-keyring.desktop" = "~/.config/autostart/unlock-keyring.desktop"
"gnome/bin/unlock-keyring.sh" = "~/.local/bin/unlock-keyring.sh"
"gnome/bin/checkupdates.sh" = "~/.local/bin/checkupdates.sh"
# TODO: split switch-theme
"gnome/bin/switch-theme.zsh" = "~/.local/bin/switch-theme.zsh"
"gnome/keyboard@ugzuzg/extension.js" = "~/.local/share/gnome-shell/extensions/keyboard@ugzuzg/extension.js"
"gnome/keyboard@ugzuzg/metadata.json" = "~/.local/share/gnome-shell/extensions/keyboard@ugzuzg/metadata.json"

[vscode.files]
"vscode/settings.json" = "~/.config/Code/User/settings.json"

[paru.files]
"paru/paru.conf" = "~/.config/paru/paru.conf"

[nvim.files]
"nvim" = "~/.config/nvim"

[tmux.files]
"tmux/tmux.conf" = { target = "~/.config/tmux/tmux.conf", type = "template" }

[volvo]
depends = ["git"]

[volvo.files]
"git/volvo/.gitconfig" = "~/volvo/.gitconfig"

[steamrommanager.files]
"deck/steamrommanager/userConfigurations.json" = "~/.config/steam-rom-manager/userData/userConfigurations.json"
"deck/steamrommanager/userSettings.json" = "~/.config/steam-rom-manager/userData/userSettings.json"

[deck]
depends = ["steamrommanager"]

[deck.files]
"deck/setup.sh" = "~/.local/bin/deck-setup.sh"
"deck/setup.desktop" = "~/Desktop/deck-setup.desktop"
"deck/Tools/Firefox.sh" = "~/Games/.bin/Tools/Firefox.sh"
"deck/Tools/Jellyfin.sh" = "~/Games/.bin/Tools/Jellyfin.sh"
"deck/Tools/Itch.sh" = "~/Games/.bin/Tools/Itch.sh"
"deck/Tools/SteamRomManager.sh" = "~/Games/.bin/Tools/SteamRomManager.sh"
"deck/Tools/Konsole.sh" = "~/Games/.bin/Tools/Konsole.sh"
"deck/Tools/Lutris.sh" = "~/Games/.bin/Tools/Lutris.sh"
"deck/Tools/Komga.sh" = "~/Games/.bin/Tools/Komga.sh"
